version: '2'
services:
  dbms:
    container_name: rdbms
    build: 
        context: .
        dockerfile: database/Dockerfile
    ports:
     - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
 
  identity:
    container_name: wso2-is
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: identity/Dockerfile
    ports:
      - "9763:9763"
      - "9443:9443"  
    environment:
      - SLEEP=1200
      
  esb:
    container_name: esb
    depends_on: 
      - dbms
      - identity
    build:
      context: .
      dockerfile: esb/Dockerfile
    ports:
      - "9764:9764"
      - "9444:9444"
      - "8281:8281"
      - "8244:8244"
    environment:
      - SLEEP=1600 
        
  das:
    container_name: apim_das
    depends_on: 
      - dbms
      - identity
    build:
      context: .
      dockerfile: das/Dockerfile
    ports:
      - "9765:9763"
      - "9445:9443"
    environment:
      - SLEEP=1600
  apim:
    container_name: apim
    depends_on: 
      - dbms
      - identity
      - das
    build:
      context: .
      dockerfile: apim/Dockerfile
    ports:
      - "9766:9766"
      - "9446:9446"
      - "8283:8283"
      - "8246:8246"
    environment:
      - SLEEP=2100
  mb:
    container_name: mb
    depends_on: 
      - dbms
      - identity
    build:
      context: .
      dockerfile: mb/Dockerfile
    ports:
      - "9767:9763"
      - "9447:9443"
    environment:
      - SLEEP=1600 
 

  
