version: '2'
services:
  dbms:
    container_name: rdbms
    build: 
        context: .
        dockerfile: database/Dockerfile
    ports:
     - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
 
  identity:
    container_name: wso2-is
    depends_on: 
      - dbms
    entrypoint: 'sh artifacts/healthcheck.sh dbms 3306'

    build:
      context: .
      dockerfile: identity/Dockerfile
    ports:
      - "9763:9763"
      - "9443:9443"  
    environment:
      - SLEEP=360
      
  esb:
    container_name: esb
    depends_on: 
      - dbms
      - identity
    entrypoint: 'sh artifacts/healthcheck.sh rdbms 3306'
    entrypoint: 'sh artifacts/healthcheck.sh wso2-is 10389'

    build:
      context: .
      dockerfile: esb/Dockerfile
    ports:
      - "9764:9763"
      - "9444:9443"
      - "8281:8280"
      - "8244:8243" 
        
  das:
    container_name: apim_das
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: das/Dockerfile
    ports:
      - "9765:9763"
      - "9445:9443"
    environment:
      - SLEEP=200 
  apim:
    container_name: apim
    depends_on: 
      - dbms
      - identity
      - das
    entrypoint: 'sh artifacts/healthcheck.sh rdbms 3306'
    entrypoint: 'sh artifacts/healthcheck.sh wso2-is 10389'
    entrypoint: 'sh artifacts/healthcheck.sh apim_das 7611'

    build:
      context: .
      dockerfile: apim/Dockerfile
    ports:
      - "9766:9763"
      - "9446:9443"
      - "8283:8280"
      - "8246:8243"
    environment:
      - SLEEP=200 
  mb:
    container_name: mb
    depends_on: 
      - dbms
      - identity
    entrypoint: 'sh artifacts/healthcheck.sh rdbms 3306'
    entrypoint: 'sh artifacts/healthcheck.sh wso2-is 10389'

    build:
      context: .
      dockerfile: mb/Dockerfile
    ports:
      - "9767:9763"
      - "9447:9443"
      
    environment:
      - SLEEP=200 
 

  